version: "3.8"

services:
  scraper:
    image: scraper:1.0
    build: 
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scraper
    restart: unless-stopped
    volumes:
      - ./json_files:/app/json_files
    depends_on: 
      - influxdb
      - standalone-chromium
  standalone-chromium:
    image: kynetiv/selenium-standalone-chromium-pi
    container_name: standalone-chromium
    restart: always
    ports:
      - "5902:4444"
    depends_on: 
      - influxdb
  buffer:
    image: buffer:1.0
    build:
      context: ./insert
      dockerfile: Dockerfile
    container_name: buffer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./json_files:/app/json_files
    depends_on: 
      - influxdb
  influxdb:
    image: hypriot/rpi-influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdbv2:/.influxdbv2
  influxdb_cli:
    links:
      - influxdb
    image: hypriot/rpi-influxdb
    container_name: influxdb_cli
    entrypoint: influx setup --bucket ${INFLUXDB_V2_BUCKET} -t ${INFLUXDB_V2_TOKEN} -o ${INFLUXDB_V2_ORG} --username=${INFLUXDB_USERNAME} --password=${INFLUXDB_PASSWORD} --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on: 
      - influxdb
volumes:
  influxdbv2: